In [26]:
import pandas as pd

df = pd.read_csv("/kaggle/input/datasets/ahmedmohamed2003/cafe-sales-dirty-data-for-cleaning-training/dirty_cafe_sales.csv")

In [27]:
df.head()

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11

In [28]:
df.shape

(10000, 8)

In [29]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    10000 non-null  object
 1   Item              9667 non-null   object
 2   Quantity          9862 non-null   object
 3   Price Per Unit    9821 non-null   object
 4   Total Spent       9827 non-null   object
 5   Payment Method    7421 non-null   object
 6   Location          6735 non-null   object
 7   Transaction Date  9841 non-null   object
dtypes: object(8)
memory usage: 625.1+ KB

In [30]:
df.describe(include="all")

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
count,10000,9667,9862,9821,9827,7421,6735,9841
unique,10000,10,7,8,19,5,4,367
top,TXN_9226047,Juice,5,3.0,6.0,Digital Wallet,Takeaway,UNKNOWN
freq,1,1171,2013,2429,979,2291,3022,159

In [31]:
df.isnull().sum()

Transaction ID         0
Item                 333
Quantity             138
Price Per Unit       179
Total Spent          173
Payment Method      2579
Location            3265
Transaction Date     159
dtype: int64

In [32]:
for col in df.columns:
    print("\n", col)
    print(df[col].value_counts().head(20))

 Transaction ID
Transaction ID
TXN_9226047    1
TXN_8567525    1
TXN_4583012    1
TXN_6796890    1
TXN_9933628    1
TXN_4302199    1
TXN_5548914    1
TXN_3528020    1
TXN_9668108    1
TXN_8076061    1
TXN_7936002    1
TXN_3124078    1
TXN_6120851    1
TXN_5762440    1
TXN_9954652    1
TXN_8866974    1
TXN_8927252    1
TXN_1736287    1
TXN_7640952    1
TXN_8467949    1
Name: count, dtype: int64

 Item
Item
Juice       1171
Coffee      1165
Salad       1148
Cake        1139
Sandwich    1131
Smoothie    1096
Cookie      1092
Tea         1089
UNKNOWN      344
ERROR        292
Name: count, dtype: int64

 Quantity
Quantity
5          2013
2          1974
4          1863
3          1849
1          1822
UNKNOWN     171
ERROR       170
Name: count, dtype: int64

 Price Per Unit
Price Per Unit
3.0        2429
4.0        2331
2.0        1227
5.0        1204
1.0        1143
1.5        1133
ERROR       190
UNKNOWN     164
Name: count, dtype: int64

 Total Spent
Total Spent
6.0        979
12.0       939
3.0        930
4.0        923
20.0       746
15.0       734
8.0        677
10.0       524
2.0        497
9.0        479
5.0        468
16.0       444
25.0       259
7.5        237
1.0        232
4.5        225
1.5        205
UNKNOWN    165
ERROR      164
Name: count, dtype: int64

 Payment Method
Payment Method
Digital Wallet    2291
Credit Card       2273
Cash              2258
ERROR              306
UNKNOWN            293
Name: count, dtype: int64

 Location
Location
Takeaway    3022
In-store    3017
ERROR        358
UNKNOWN      338
Name: count, dtype: int64

 Transaction Date
Transaction Date
UNKNOWN       159
ERROR         142
2023-06-16     40
2023-02-06     40
2023-09-21     39
2023-03-13     39
2023-07-24     39
2023-07-21     39
2023-01-05     38
2023-10-22     37
2023-01-25     37
2023-06-18     37
2023-04-30     36
2023-11-07     36
2023-11-23     36
2023-06-30     36
2023-01-12     36
2023-08-07     36
2023-06-28     35
2023-04-06     35
Name: count, dtype: int64

In [33]:
for col in df.columns:
    unknown = (df[col] == "UNKNOWN").sum()
    error = (df[col] == "ERROR").sum()
    
    print(col, "→ UNKNOWN:", unknown, "| ERROR:", error)

Transaction ID → UNKNOWN: 0 | ERROR: 0
Item → UNKNOWN: 344 | ERROR: 292
Quantity → UNKNOWN: 171 | ERROR: 170
Price Per Unit → UNKNOWN: 164 | ERROR: 190
Total Spent → UNKNOWN: 165 | ERROR: 164
Payment Method → UNKNOWN: 293 | ERROR: 306
Location → UNKNOWN: 338 | ERROR: 358
Transaction Date → UNKNOWN: 159 | ERROR: 142

In [35]:
print("Quantity:", df["Quantity"].unique())
print("Price Per Unit:", df["Price Per Unit"].unique())
print("Total Spent:", df["Total Spent"].unique())

Quantity: ['2' '4' '5' '3' '1' 'ERROR' 'UNKNOWN' nan]
Price Per Unit: ['2.0' '3.0' '1.0' '5.0' '4.0' '1.5' nan 'ERROR' 'UNKNOWN']
Total Spent: ['4.0' '12.0' 'ERROR' '10.0' '20.0' '9.0' '16.0' '15.0' '25.0' '8.0' '5.0'
 '3.0' '6.0' nan 'UNKNOWN' '2.0' '1.0' '7.5' '4.5' '1.5']

In [38]:
numeric_columns = ["Quantity", "Price Per Unit", "Total Spent"]

for col in numeric_columns:
    df[col] = pd.to_numeric(df[col], errors="coerce")

In [39]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    10000 non-null  object
 1   Item              9667 non-null   object
 2   Quantity          9521 non-null   float64
 3   Price Per Unit    9467 non-null   float64
 4   Total Spent       9498 non-null   float64
 5   Payment Method    7421 non-null   object
 6   Location          6735 non-null   object
 7   Transaction Date  9841 non-null   object
dtypes: float64(3), object(5)
memory usage: 625.1+ KB

In [40]:
df.isnull().sum()

Transaction ID         0
Item                 333
Quantity             479
Price Per Unit       533
Total Spent          502
Payment Method      2579
Location            3265
Transaction Date     159
dtype: int64

In [41]:
df.isnull().sum(axis=1).value_counts().sort_index()

0    4096
1    4185
2    1506
3     199
4      14
Name: count, dtype: int64

In [42]:
df.isnull().sum().sort_values(ascending=False)

Location            3265
Payment Method      2579
Price Per Unit       533
Total Spent          502
Quantity             479
Item                 333
Transaction Date     159
Transaction ID         0
dtype: int64

In [43]:

df[["Quantity", "Price Per Unit", "Total Spent"]].notnull().all(axis=1).sum()

np.int64(8544)

In [44]:
df["calculated_total"] = df["Quantity"] * df["Price Per Unit"]

(df["calculated_total"] == df["Total Spent"]).sum()

np.int64(8544)

In [45]:
condition = (
    df["Quantity"].notnull() &
    df["Price Per Unit"].notnull() &
    df["Total Spent"].isnull()
)

condition.sum()

np.int64(462)

In [46]:
df.loc[condition, ["Transaction ID", "Quantity", "Price Per Unit", "Total Spent"]].head(10)

    Transaction ID  Quantity  Price Per Unit  Total Spent
2      TXN_4271903       4.0             1.0          NaN
25     TXN_7958992       3.0             4.0          NaN
31     TXN_8927252       2.0             1.0          NaN
42     TXN_6650263       2.0             1.5          NaN
94     TXN_6289610       3.0             3.0          NaN
143    TXN_8495063       1.0             3.0          NaN
146    TXN_7623634       2.0             3.0          NaN
171    TXN_8989148       2.0             1.5          NaN
238    TXN_5526852       5.0             4.0          NaN
253    TXN_3544789       4.0             1.5          NaN

In [47]:
df.loc[condition, "Total Spent"] = (
    df.loc[condition, "Quantity"] * df.loc[condition, "Price Per Unit"]
)

In [48]:
df["Total Spent"].isnull().sum()

np.int64(40)

In [49]:
df.loc[
    df["Total Spent"].isnull(),
    ["Transaction ID", "Quantity", "Price Per Unit", "Total Spent"]
]

     Transaction ID  Quantity  Price Per Unit  Total Spent
65      TXN_4987129       3.0             NaN          NaN
236     TXN_8562645       NaN             5.0          NaN
278     TXN_3229409       NaN             3.0          NaN
641     TXN_2962976       NaN             3.0          NaN
738     TXN_8696094       NaN             4.0          NaN
1674    TXN_9367492       2.0             NaN          NaN
1761    TXN_3611851       4.0             NaN          NaN
2229    TXN_8498613       2.0             NaN          NaN
2289    TXN_7524977       4.0             NaN          NaN
2585    TXN_1259340       3.0             NaN          NaN
2796    TXN_9188692       NaN             3.0          NaN
3162    TXN_3577949       3.0             NaN          NaN
3203    TXN_4565754       NaN             4.0          NaN
3224    TXN_6297232       NaN             2.0          NaN
3401    TXN_3251829       NaN             1.5          NaN
3598    TXN_2857444       1.0             NaN          NaN
3673    TXN_6500126       2.0             NaN          NaN
4021    TXN_6424202       2.0             NaN          NaN
4152    TXN_9646000       2.0             NaN          NaN
4257    TXN_6470865       NaN             2.0          NaN
5841    TXN_5884081       NaN             1.0          NaN
7029    TXN_4628338       NaN             2.0          NaN
7035    TXN_8872984       5.0             NaN          NaN
7230    TXN_5118799       2.0             NaN          NaN
7244    TXN_2253622       5.0             NaN          NaN
7297    TXN_9944500       NaN             4.0          NaN
7568    TXN_3705445       5.0             NaN          NaN
7686    TXN_6905143       5.0             NaN          NaN
8021    TXN_2428781       NaN             5.0          NaN
8128    TXN_6105807       3.0             NaN          NaN
8443    TXN_2023651       NaN             4.0          NaN
8465    TXN_9669616       NaN             2.0          NaN
8479    TXN_1547245       NaN             4.0          NaN
8497    TXN_1525583       3.0             NaN          NaN
8574    TXN_2546684       NaN             3.0          NaN
8732    TXN_4550558       NaN             1.0          NaN
9212    TXN_7322317       1.0             NaN          NaN
9590    TXN_9924732       NaN             4.0          NaN
9869    TXN_1975184       NaN             2.0          NaN
9893    TXN_3809533       2.0             NaN          NaN

In [50]:
df.groupby("Item")["Price Per Unit"].unique()

Item
Cake                                 [3.0, nan]
Coffee                               [2.0, nan]
Cookie                               [1.0, nan]
ERROR       [1.5, 3.0, 5.0, nan, 4.0, 2.0, 1.0]
Juice                                [3.0, nan]
Salad                                [5.0, nan]
Sandwich                             [4.0, nan]
Smoothie                             [4.0, nan]
Tea                                  [1.5, nan]
UNKNOWN     [3.0, 1.0, 5.0, 4.0, 1.5, 2.0, nan]
Name: Price Per Unit, dtype: object

In [51]:
df.loc[
    df["Total Spent"].isnull(),
    ["Transaction ID", "Item", "Quantity", "Price Per Unit", "Total Spent"]
]

     Transaction ID      Item  Quantity  Price Per Unit  Total Spent
65      TXN_4987129  Sandwich       3.0             NaN          NaN
236     TXN_8562645     Salad       NaN             5.0          NaN
278     TXN_3229409     Juice       NaN             3.0          NaN
641     TXN_2962976     Juice       NaN             3.0          NaN
738     TXN_8696094  Sandwich       NaN             4.0          NaN
1674    TXN_9367492       Tea       2.0             NaN          NaN
1761    TXN_3611851       NaN       4.0             NaN          NaN
2229    TXN_8498613  Sandwich       2.0             NaN          NaN
2289    TXN_7524977   UNKNOWN       4.0             NaN          NaN
2585    TXN_1259340       Tea       3.0             NaN          NaN
2796    TXN_9188692      Cake       NaN             3.0          NaN
3162    TXN_3577949      Cake       3.0             NaN          NaN
3203    TXN_4565754  Smoothie       NaN             4.0          NaN
3224    TXN_6297232    Coffee       NaN             2.0          NaN
3401    TXN_3251829       Tea       NaN             1.5          NaN
3598    TXN_2857444  Smoothie       1.0             NaN          NaN
3673    TXN_6500126  Smoothie       2.0             NaN          NaN
4021    TXN_6424202    Cookie       2.0             NaN          NaN
4152    TXN_9646000     ERROR       2.0             NaN          NaN
4257    TXN_6470865    Coffee       NaN             2.0          NaN
5841    TXN_5884081    Cookie       NaN             1.0          NaN
7029    TXN_4628338    Coffee       NaN             2.0          NaN
7035    TXN_8872984     Salad       5.0             NaN          NaN
7230    TXN_5118799    Cookie       2.0             NaN          NaN
7244    TXN_2253622  Sandwich       5.0             NaN          NaN
7297    TXN_9944500  Smoothie       NaN             4.0          NaN
7568    TXN_3705445    Cookie       5.0             NaN          NaN
7686    TXN_6905143    Coffee       5.0             NaN          NaN
8021    TXN_2428781     Salad       NaN             5.0          NaN
8128    TXN_6105807  Smoothie       3.0             NaN          NaN
8443    TXN_2023651  Sandwich       NaN             4.0          NaN
8465    TXN_9669616    Coffee       NaN             2.0          NaN
8479    TXN_1547245  Sandwich       NaN             4.0          NaN
8497    TXN_1525583  Sandwich       3.0             NaN          NaN
8574    TXN_2546684     Juice       NaN             3.0          NaN
8732    TXN_4550558    Cookie       NaN             1.0          NaN
9212    TXN_7322317       Tea       1.0             NaN          NaN
9590    TXN_9924732  Sandwich       NaN             4.0          NaN
9869    TXN_1975184    Coffee       NaN             2.0          NaN
9893    TXN_3809533     Juice       2.0             NaN          NaN

In [52]:
item_price = (
    df[df["Item"].notna() & 
       ~df["Item"].isin(["UNKNOWN", "ERROR"])]
    .groupby("Item")["Price Per Unit"]
    .first()
)

item_price

Item
Cake        3.0
Coffee      2.0
Cookie      1.0
Juice       3.0
Salad       5.0
Sandwich    4.0
Smoothie    4.0
Tea         1.5
Name: Price Per Unit, dtype: float64

In [53]:
df["Price Per Unit"] = df["Price Per Unit"].fillna(
    df["Item"].map(item_price)
)

In [54]:
df["Price Per Unit"].isnull().sum()

np.int64(54)

In [55]:
df.loc[
    df["Price Per Unit"].isnull(),
    ["Transaction ID", "Item", "Quantity", "Price Per Unit", "Total Spent"]
]

     Transaction ID     Item  Quantity  Price Per Unit  Total Spent
118     TXN_4633784    ERROR       5.0             NaN         15.0
151     TXN_4031509      NaN       4.0             NaN         16.0
289     TXN_3495950      NaN       4.0             NaN          6.0
334     TXN_2523298      NaN       4.0             NaN          6.0
550     TXN_4186681    ERROR       4.0             NaN          6.0
750     TXN_5787508    ERROR       3.0             NaN          9.0
818     TXN_7940202      NaN       1.0             NaN          4.0
1154    TXN_2473090  UNKNOWN       2.0             NaN          3.0
1337    TXN_5031214    ERROR       5.0             NaN          5.0
1377    TXN_8396271    ERROR       2.0             NaN          2.0
1589    TXN_5245399      NaN       5.0             NaN         10.0
1761    TXN_3611851      NaN       4.0             NaN          NaN
1786    TXN_1923349    ERROR       4.0             NaN          6.0
2002    TXN_5206049      NaN       3.0             NaN          3.0
2227    TXN_3200203    ERROR       2.0             NaN          8.0
2289    TXN_7524977  UNKNOWN       4.0             NaN          NaN
2596    TXN_4844386      NaN       5.0             NaN         15.0
2610    TXN_8266689      NaN       5.0             NaN         15.0
2962    TXN_9702662  UNKNOWN       4.0             NaN         16.0
3013    TXN_1842697  UNKNOWN       5.0             NaN         15.0
3404    TXN_7797231      NaN       5.0             NaN         10.0
3434    TXN_6457997  UNKNOWN       1.0             NaN          4.0
3666    TXN_8616276  UNKNOWN       2.0             NaN          3.0
3739    TXN_4849180  UNKNOWN       5.0             NaN         15.0
3779    TXN_7376255  UNKNOWN       NaN             NaN         25.0
3900    TXN_5093855      NaN       4.0             NaN          6.0
4092    TXN_1840897  UNKNOWN       1.0             NaN          5.0
4152    TXN_9646000    ERROR       2.0             NaN          NaN
4621    TXN_7844352    ERROR       2.0             NaN          6.0
5039    TXN_9514452    ERROR       5.0             NaN         10.0
5891    TXN_9618962      NaN       3.0             NaN          6.0
5991    TXN_2913107  UNKNOWN       4.0             NaN          8.0
6177    TXN_3232279  UNKNOWN       4.0             NaN         16.0
6345    TXN_4208919      NaN       3.0             NaN         12.0
6429    TXN_2536573      NaN       2.0             NaN          8.0
6849    TXN_7928378      NaN       3.0             NaN         12.0
7478    TXN_9710982  UNKNOWN       4.0             NaN         16.0
7597    TXN_1082717    ERROR       NaN             NaN          9.0
8129    TXN_8384699  UNKNOWN       3.0             NaN         15.0
8458    TXN_7595907      NaN       5.0             NaN         15.0
8463    TXN_2150872  UNKNOWN       5.0             NaN         15.0
8817    TXN_8365530      NaN       4.0             NaN         16.0
8959    TXN_3803063      NaN       4.0             NaN         12.0
9174    TXN_5935353      NaN       2.0             NaN          8.0
9234    TXN_8918253  UNKNOWN       3.0             NaN         12.0
9382    TXN_4255580    ERROR       1.0             NaN          3.0
9425    TXN_2065683  UNKNOWN       3.0             NaN          6.0
9454    TXN_1637131    ERROR       4.0             NaN          6.0
9673    TXN_2480808  UNKNOWN       1.0             NaN          4.0
9717    TXN_3334632      NaN       1.0             NaN          2.0
9764    TXN_1688292  UNKNOWN       3.0             NaN          9.0
9819    TXN_1208561      NaN       NaN             NaN         20.0
9820    TXN_8751702      NaN       5.0             NaN         15.0
9996    TXN_9659401      NaN       3.0             NaN          3.0

In [56]:
condition_price = (
    df["Price Per Unit"].isnull() &
    df["Quantity"].notnull() &
    df["Total Spent"].notnull()
)

condition_price.sum()

np.int64(48)

In [57]:
df.loc[condition_price, "Total Spent"] / df.loc[condition_price, "Quantity"]

118     3.0
151     4.0
289     1.5
334     1.5
550     1.5
750     3.0
818     4.0
1154    1.5
1337    1.0
1377    1.0
1589    2.0
1786    1.5
2002    1.0
2227    4.0
2596    3.0
2610    3.0
2962    4.0
3013    3.0
3404    2.0
3434    4.0
3666    1.5
3739    3.0
3900    1.5
4092    5.0
4621    3.0
5039    2.0
5891    2.0
5991    2.0
6177    4.0
6345    4.0
6429    4.0
6849    4.0
7478    4.0
8129    5.0
8458    3.0
8463    3.0
8817    4.0
8959    3.0
9174    4.0
9234    4.0
9382    3.0
9425    2.0
9454    1.5
9673    4.0
9717    2.0
9764    3.0
9820    3.0
9996    1.0
dtype: float64

In [58]:
df.loc[condition_price, "Price Per Unit"] = (
    df.loc[condition_price, "Total Spent"] /
    df.loc[condition_price, "Quantity"]
)

In [59]:
df["Price Per Unit"].isnull().sum()

np.int64(6)

In [60]:
df.loc[
    df["Price Per Unit"].isnull(),
    ["Transaction ID", "Item", "Quantity", "Price Per Unit", "Total Spent"]
]

     Transaction ID     Item  Quantity  Price Per Unit  Total Spent
1761    TXN_3611851      NaN       4.0             NaN          NaN
2289    TXN_7524977  UNKNOWN       4.0             NaN          NaN
3779    TXN_7376255  UNKNOWN       NaN             NaN         25.0
4152    TXN_9646000    ERROR       2.0             NaN          NaN
7597    TXN_1082717    ERROR       NaN             NaN          9.0
9819    TXN_1208561      NaN       NaN             NaN         20.0

In [61]:
df[["Quantity", "Price Per Unit", "Total Spent"]].isnull().sum()

Quantity          479
Price Per Unit      6
Total Spent        40
dtype: int64

In [62]:
condition_quantity = (
    df["Quantity"].isnull() &
    df["Price Per Unit"].notnull() &
    df["Total Spent"].notnull()
)

condition_quantity.sum()

np.int64(456)

In [63]:
df.loc[condition_quantity, "Total Spent"] / df.loc[condition_quantity, "Price Per Unit"]

20      5.0
55      2.0
57      1.0
66      2.0
117     3.0
       ...
9932    2.0
9935    4.0
9944    5.0
9957    4.0
9984    1.0
Length: 456, dtype: float64

In [64]:
df.loc[condition_quantity, "Quantity"] = (
    df.loc[condition_quantity, "Total Spent"] /
    df.loc[condition_quantity, "Price Per Unit"]
)

In [65]:
df["Quantity"].isnull().sum()

np.int64(23)

In [66]:
df.loc[
    df["Quantity"].isnull(),
    ["Transaction ID", "Item", "Quantity", "Price Per Unit", "Total Spent"]
]

     Transaction ID      Item  Quantity  Price Per Unit  Total Spent
236     TXN_8562645     Salad       NaN             5.0          NaN
278     TXN_3229409     Juice       NaN             3.0          NaN
641     TXN_2962976     Juice       NaN             3.0          NaN
738     TXN_8696094  Sandwich       NaN             4.0          NaN
2796    TXN_9188692      Cake       NaN             3.0          NaN
3203    TXN_4565754  Smoothie       NaN             4.0          NaN
3224    TXN_6297232    Coffee       NaN             2.0          NaN
3401    TXN_3251829       Tea       NaN             1.5          NaN
3779    TXN_7376255   UNKNOWN       NaN             NaN         25.0
4257    TXN_6470865    Coffee       NaN             2.0          NaN
5841    TXN_5884081    Cookie       NaN             1.0          NaN
7029    TXN_4628338    Coffee       NaN             2.0          NaN
7297    TXN_9944500  Smoothie       NaN             4.0          NaN
7597    TXN_1082717     ERROR       NaN             NaN          9.0
8021    TXN_2428781     Salad       NaN             5.0          NaN
8443    TXN_2023651  Sandwich       NaN             4.0          NaN
8465    TXN_9669616    Coffee       NaN             2.0          NaN
8479    TXN_1547245  Sandwich       NaN             4.0          NaN
8574    TXN_2546684     Juice       NaN             3.0          NaN
8732    TXN_4550558    Cookie       NaN             1.0          NaN
9590    TXN_9924732  Sandwich       NaN             4.0          NaN
9819    TXN_1208561       NaN       NaN             NaN         20.0
9869    TXN_1975184    Coffee       NaN             2.0          NaN

In [67]:
df[["Quantity", "Price Per Unit", "Total Spent"]].isnull().sum()

Quantity          23
Price Per Unit     6
Total Spent       40
dtype: int64

In [68]:
df["Item"].value_counts(dropna=False)

Item
Juice       1171
Coffee      1165
Salad       1148
Cake        1139
Sandwich    1131
Smoothie    1096
Cookie      1092
Tea         1089
UNKNOWN      344
NaN          333
ERROR        292
Name: count, dtype: int64

In [71]:
import numpy as np

In [72]:
df["Item"] = df["Item"].replace(["UNKNOWN", "ERROR"], np.nan)

In [73]:
df["Item"].isnull().sum()

np.int64(969)

In [74]:
df["Payment Method"].value_counts(dropna=False)

Payment Method
NaN               2579
Digital Wallet    2291
Credit Card       2273
Cash              2258
ERROR              306
UNKNOWN            293
Name: count, dtype: int64

In [75]:
df["Payment Method"] = df["Payment Method"].replace(
    ["UNKNOWN", "ERROR"], np.nan
)

In [76]:
df["Payment Method"].isnull().sum()

np.int64(3178)

In [77]:
df["Location"].value_counts(dropna=False)

Location
NaN         3265
Takeaway    3022
In-store    3017
ERROR        358
UNKNOWN      338
Name: count, dtype: int64

In [78]:
df["Location"] = df["Location"].replace(
    ["UNKNOWN", "ERROR"], np.nan
)

In [79]:
df["Location"].isnull().sum()

np.int64(3961)

In [80]:
df["Transaction Date"].value_counts(dropna=False).head(20)

Transaction Date
UNKNOWN       159
NaN           159
ERROR         142
2023-06-16     40
2023-02-06     40
2023-09-21     39
2023-07-21     39
2023-07-24     39
2023-03-13     39
2023-01-05     38
2023-10-22     37
2023-06-18     37
2023-01-25     37
2023-04-30     36
2023-08-07     36
2023-11-07     36
2023-06-30     36
2023-01-12     36
2023-11-23     36
2023-10-08     35
Name: count, dtype: int64

In [81]:
df["Transaction Date"] = df["Transaction Date"].replace(
    ["UNKNOWN", "ERROR"], np.nan
)

In [82]:
df["Transaction Date"].isnull().sum()

np.int64(460)

In [83]:
df["Transaction Date"] = pd.to_datetime(
    df["Transaction Date"],
    errors="coerce"
)

In [84]:
df["Transaction Date"].dtype

dtype('<M8[ns]')

In [85]:
df["Transaction Date"].isnull().sum()

np.int64(460)

In [86]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    10000 non-null  object
 1   Item              9031 non-null   object
 2   Quantity          9977 non-null   float64
 3   Price Per Unit    9994 non-null   float64
 4   Total Spent       9960 non-null   float64
 5   Payment Method    6822 non-null   object
 6   Location          6039 non-null   object
 7   Transaction Date  9540 non-null   datetime64[ns]
 8   calculated_total  9006 non-null   float64
dtypes: datetime64[ns](1), float64(4), object(4)
memory usage: 703.3+ KB

In [87]:
df["calculated_total"] = df["Quantity"] * df["Price Per Unit"]

df["total_check"] = np.isclose(
    df["Total Spent"],
    df["calculated_total"],
    equal_nan=True
)

df["total_check"].value_counts()

total_check
True     9980
False      20
Name: count, dtype: int64

In [88]:
df.loc[
    ~df["total_check"],
    [
        "Transaction ID",
        "Item",
        "Quantity",
        "Price Per Unit",
        "Total Spent",
        "calculated_total"
    ]
]

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,calculated_total
65,TXN_4987129,Sandwich,3.0,4.0,NaN,12.0
1674,TXN_9367492,Tea,2.0,1.5,NaN,3.0
2229,TXN_8498613,Sandwich,2.0,4.0,NaN,8.0
2585,TXN_1259340,Tea,3.0,1.5,NaN,4.5
3162,TXN_3577949,Cake,3.0,3.0,NaN,9.0
3598,TXN_2857444,Smoothie,1.0,4.0,NaN,4.0
3673,TXN_6500126,Smoothie,2.0,4.0,NaN,8.0
3779,TXN_7376255,NaN,NaN,NaN,25.0,NaN
4021,TXN_6424202,Cookie,2.0,1.0,NaN,2.0
7035,TXN_8872984,Salad,5.0,5.0,NaN,25.0
7230,TXN_5118799,Cookie,2.0,1.0,NaN,2.0
7244,TXN_2253622,Sandwich,5.0,4.0,NaN,20.0
7568,TXN_3705445,Cookie,5.0,1.0,NaN,5.0
7597,TXN_1082717,NaN,NaN,NaN,9.0,NaN
7686,TXN_6905143,Coffee,5.0,2.0,NaN,10.0
8128,TXN_6105807,Smoothie,3.0,4.0,NaN,12.0
8497,TXN_1525583,Sandwich,3.0,4.0,NaN,12.0
9212,TXN_7322317,Tea,1.0,1.5,NaN,1.5
9819,TXN_1208561,NaN,NaN,NaN,20.0,NaN
9893,TXN_3809533,Juice,2.0,3.0,NaN,6.0

In [89]:
condition_total = (
    df["Total Spent"].isnull() &
    df["Quantity"].notnull() &
    df["Price Per Unit"].notnull()
)

condition_total.sum()

np.int64(17)

In [90]:
df.loc[condition_total, "Quantity"] * df.loc[condition_total, "Price Per Unit"]

65      12.0
1674     3.0
2229     8.0
2585     4.5
3162     9.0
3598     4.0
3673     8.0
4021     2.0
7035    25.0
7230     2.0
7244    20.0
7568     5.0
7686    10.0
8128    12.0
8497    12.0
9212     1.5
9893     6.0
dtype: float64

In [91]:
df.loc[condition_total, "Total Spent"] = (
    df.loc[condition_total, "Quantity"] *
    df.loc[condition_total, "Price Per Unit"]
)

In [92]:
df["Total Spent"].isnull().sum()

np.int64(23)

In [93]:
df.loc[
    df["Total Spent"].isnull(),
    [
        "Transaction ID",
        "Item",
        "Quantity",
        "Price Per Unit",
        "Total Spent"
    ]
]

     Transaction ID      Item  Quantity  Price Per Unit  Total Spent
236     TXN_8562645     Salad       NaN             5.0          NaN
278     TXN_3229409     Juice       NaN             3.0          NaN
641     TXN_2962976     Juice       NaN             3.0          NaN
738     TXN_8696094  Sandwich       NaN             4.0          NaN
1761    TXN_3611851       NaN       4.0             NaN          NaN
2289    TXN_7524977       NaN       4.0             NaN          NaN
2796    TXN_9188692      Cake       NaN             3.0          NaN
3203    TXN_4565754  Smoothie       NaN             4.0          NaN
3224    TXN_6297232    Coffee       NaN             2.0          NaN
3401    TXN_3251829       Tea       NaN             1.5          NaN
4152    TXN_9646000       NaN       2.0             NaN          NaN
4257    TXN_6470865    Coffee       NaN             2.0          NaN
5841    TXN_5884081    Cookie       NaN             1.0          NaN
7029    TXN_4628338    Coffee       NaN             2.0          NaN
7297    TXN_9944500  Smoothie       NaN             4.0          NaN
8021    TXN_2428781     Salad       NaN             5.0          NaN
8443    TXN_2023651  Sandwich       NaN             4.0          NaN
8465    TXN_9669616    Coffee       NaN             2.0          NaN
8479    TXN_1547245  Sandwich       NaN             4.0          NaN
8574    TXN_2546684     Juice       NaN             3.0          NaN
8732    TXN_4550558    Cookie       NaN             1.0          NaN
9590    TXN_9924732  Sandwich       NaN             4.0          NaN
9869    TXN_1975184    Coffee       NaN             2.0          NaN

In [94]:
df.drop(columns=["calculated_total", "total_check"], inplace=True)

In [95]:
df.shape

(10000, 8)

In [96]:
df.duplicated().sum()

np.int64(0)

In [97]:
df["Transaction ID"].duplicated().sum()

np.int64(0)

In [98]:
df[["Quantity", "Price Per Unit", "Total Spent"]].describe()

          Quantity  Price Per Unit  Total Spent
count  9977.000000     9994.000000  9977.000000
mean      3.024957        2.947018     8.930139
std       1.420395        1.280006     6.004921
min       1.000000        1.000000     1.000000
25%       2.000000        2.000000     4.000000
50%       3.000000        3.000000     8.000000
75%       4.000000        4.000000    12.000000
max       5.000000        5.000000    25.000000

In [99]:
for col in ["Item", "Payment Method", "Location"]:
    print("\n", col)
    print(df[col].value_counts(dropna=False))

 Item
Item
Juice       1171
Coffee      1165
Salad       1148
Cake        1139
Sandwich    1131
Smoothie    1096
Cookie      1092
Tea         1089
NaN          969
Name: count, dtype: int64

 Payment Method
Payment Method
NaN               3178
Digital Wallet    2291
Credit Card       2273
Cash              2258
Name: count, dtype: int64

 Location
Location
NaN         3961
Takeaway    3022
In-store    3017
Name: count, dtype: int64

In [100]:
missing_report = df.isnull().sum()

missing_report

Transaction ID         0
Item                 969
Quantity              23
Price Per Unit         6
Total Spent           23
Payment Method      3178
Location            3961
Transaction Date     460
dtype: int64

In [101]:
missing_percentage = (df.isnull().sum() / len(df)) * 100

missing_percentage.sort_values(ascending=False)

Location            39.61
Payment Method      31.78
Item                 9.69
Transaction Date     4.60
Quantity             0.23
Total Spent          0.23
Price Per Unit       0.06
Transaction ID       0.00
dtype: float64

In [102]:
for col in df.columns:
    unknown = (df[col] == "UNKNOWN").sum()
    error = (df[col] == "ERROR").sum()

    print(col, "→ UNKNOWN:", unknown, "| ERROR:", error)

Transaction ID → UNKNOWN: 0 | ERROR: 0
Item → UNKNOWN: 0 | ERROR: 0
Quantity → UNKNOWN: 0 | ERROR: 0
Price Per Unit → UNKNOWN: 0 | ERROR: 0
Total Spent → UNKNOWN: 0 | ERROR: 0
Payment Method → UNKNOWN: 0 | ERROR: 0
Location → UNKNOWN: 0 | ERROR: 0
Transaction Date → UNKNOWN: 0 | ERROR: 0

In [103]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    10000 non-null  object
 1   Item              9031 non-null   object
 2   Quantity          9977 non-null   float64
 3   Price Per Unit    9994 non-null   float64
 4   Total Spent       9977 non-null   float64
 5   Payment Method    6822 non-null   object
 6   Location          6039 non-null   object
 7   Transaction Date  9540 non-null   datetime64[ns]
dtypes: datetime64[ns](1), float64(3), object(4)
memory usage: 625.1+ KB

In [104]:
df.shape

(10000, 8)

In [105]:
df.to_csv("cafe_sales_cleaned.csv", index=False)

In [106]:
import os

os.path.exists("cafe_sales_cleaned.csv")

True